export const GAME_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_GAME_CONTRACT_ADDRESS || ""
 let boom

export const GAME_CONTRACT_ABI = [
  // Constructor
  {
    inputs: [
      { internalType: "uint256", name: "_gameDuration", type: "uint256" },
      { internalType: "uint256", name: "_minRewardAmount", type: "uint256" },
      { internalType: "uint256", name: "_maxRewardAmount", type: "uint256" },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  // View Functions
  {
    inputs: [],
    name: "MAX_FRIENDS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "activeGameTemplateIds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_player1", type: "address" },
      { internalType: "address", name: "_player2", type: "address" },
    ],
    name: "areFriends",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_answer", type: "string" }],
    name: "calculateAnswerHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "enum GameContract.Difficulty", name: "", type: "uint8" }],
    name: "difficultyMultipliers",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "friendCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "friends",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "gameDuration",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "gameTemplates",
    outputs: [
      { internalType: "bytes32", name: "answerHash", type: "bytes32" },
      { internalType: "uint256", name: "baseRewardAmount", type: "uint256" },
      { internalType: "enum GameContract.Difficulty", name: "difficulty", type: "uint8" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getActiveGameTemplateCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentGame",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "gameId", type: "uint256" },
          { internalType: "bytes32", name: "answerHash", type: "bytes32" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "uint256", name: "rewardAmount", type: "uint256" },
          { internalType: "enum GameContract.Difficulty", name: "difficulty", type: "uint8" },
          { internalType: "uint256", name: "hintCost", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
          { internalType: "uint256", name: "totalSubmissions", type: "uint256" },
          { internalType: "uint256", name: "correctAnswers", type: "uint256" },
        ],
        internalType: "struct GameContract.Game",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_player", type: "address" },
      { internalType: "uint256", name: "_count", type: "uint256" },
    ],
    name: "getFriendLeaderboard",
    outputs: [
      {
        components: [
          { internalType: "address", name: "player", type: "address" },
          { internalType: "uint256", name: "score", type: "uint256" },
          { internalType: "bool", name: "isFriend", type: "bool" },
        ],
        internalType: "struct GameContract.FriendLeaderboardEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_player", type: "address" }],
    name: "getFriends",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_player", type: "address" }],
    name: "getPlayerAchievements",
    outputs: [{ internalType: "bool[]", name: "", type: "bool[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_player", type: "address" }],
    name: "getPlayerGame",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "gameId", type: "uint256" },
          { internalType: "bytes32", name: "answerHash", type: "bytes32" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "uint256", name: "rewardAmount", type: "uint256" },
          { internalType: "enum GameContract.Difficulty", name: "difficulty", type: "uint8" },
          { internalType: "uint256", name: "hintCost", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
          { internalType: "uint256", name: "totalSubmissions", type: "uint256" },
          { internalType: "uint256", name: "correctAnswers", type: "uint256" },
        ],
        internalType: "struct GameContract.Game",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_player", type: "address" }],
    name: "getPlayerScore",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_count", type: "uint256" }],
    name: "getGlobalLeaderboard",
    outputs: [
      {
        components: [
          { internalType: "address", name: "player", type: "address" },
          { internalType: "uint256", name: "score", type: "uint256" },
        ],
        internalType: "struct GameContract.LeaderboardEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_templateId", type: "uint256" }],
    name: "getGameTemplate",
    outputs: [
      {
        components: [
          { internalType: "bytes32", name: "answerHash", type: "bytes32" },
          { internalType: "uint256", name: "baseRewardAmount", type: "uint256" },
          { internalType: "enum GameContract.Difficulty", name: "difficulty", type: "uint8" },
          { internalType: "bool", name: "isActive", type: "bool" },
        ],
        internalType: "struct GameContract.GameTemplate",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_player", type: "address" }],
    name: "getPlayerStats",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "totalGamesPlayed", type: "uint256" },
          { internalType: "uint256", name: "correctAnswers", type: "uint256" },
          { internalType: "uint256", name: "totalRewardsEarned", type: "uint256" },
          { internalType: "uint256", name: "lastPlayedTime", type: "uint256" },
          { internalType: "uint256", name: "hintsPurchased", type: "uint256" },
          { internalType: "uint256", name: "currentStreak", type: "uint256" },
          { internalType: "uint256", name: "bestStreak", type: "uint256" },
        ],
        internalType: "struct GameContract.PlayerStatsView",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_count", type: "uint256" }],
    name: "getTopPlayers",
    outputs: [
      {
        components: [
          { internalType: "address", name: "player", type: "address" },
          { internalType: "uint256", name: "score", type: "uint256" },
        ],
        internalType: "struct GameContract.LeaderboardEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_player", type: "address" },
      { internalType: "enum GameContract.Achievement", name: "_achievement", type: "uint8" },
    ],
    name: "hasAchievement",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  // Write Functions
  {
    inputs: [{ internalType: "address", name: "_friend", type: "address" }],
    name: "addFriend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_answerHash", type: "bytes32" },
      { internalType: "uint256", name: "_baseRewardAmount", type: "uint256" },
      { internalType: "enum GameContract.Difficulty", name: "_difficulty", type: "uint8" },
    ],
    name: "addGameTemplate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "buyHint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_templateId", type: "uint256" }],
    name: "deactivateGameTemplate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositFunds",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getNewGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_friend", type: "address" }],
    name: "removeFriend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_answer", type: "string" }],
    name: "submitGuess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "withdrawFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "startPlayerGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const
