export const GAME_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_GAME_CONTRACT_ADDRESS || ''

// Minimal ABI for the game contract - add full ABI as needed
export const GAME_CONTRACT_ABI = [
  {
    name: 'startPlayerGame',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'submitGuess',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_guess', type: 'string' }],
    outputs: [],
  },
  {
    name: 'buyHint',
    type: 'function',
    stateMutability: 'payable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'addFriend',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_friend', type: 'address' }],
    outputs: [],
  },
  {
    name: 'removeFriend',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_friend', type: 'address' }],
    outputs: [],
  },
  {
    name: 'getNewGame',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'depositFunds',
    type: 'function',
    stateMutability: 'payable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'getCurrentGame',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'tuple', components: [
      { name: 'gameId', type: 'uint256' },
      { name: 'answerHash', type: 'bytes32' },
      { name: 'startTime', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'rewardAmount', type: 'uint256' },
      { name: 'difficulty', type: 'uint8' },
      { name: 'hintCost', type: 'uint256' },
      { name: 'isActive', type: 'bool' },
      { name: 'totalSubmissions', type: 'uint256' },
      { name: 'correctAnswers', type: 'uint256' },
    ]}],
  },
  {
    name: 'getPlayerStats',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '_player', type: 'address' }],
    outputs: [{ name: '', type: 'tuple', components: [
      { name: 'totalGamesPlayed', type: 'uint256' },
      { name: 'correctAnswers', type: 'uint256' },
      { name: 'totalRewardsEarned', type: 'uint256' },
      { name: 'lastPlayedTime', type: 'uint256' },
      { name: 'hintsPurchased', type: 'uint256' },
      { name: 'currentStreak', type: 'uint256' },
      { name: 'bestStreak', type: 'uint256' },
    ]}],
  },
  {
    name: 'getPlayerScore',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '_player', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'getTopPlayers',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '_count', type: 'uint256' }],
    outputs: [{ name: '', type: 'tuple[]', components: [
      { name: 'player', type: 'address' },
      { name: 'score', type: 'uint256' },
    ]}],
  },
  {
    name: 'getFriendLeaderboard',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: '_player', type: 'address' },
      { name: '_count', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'tuple[]', components: [
      { name: 'player', type: 'address' },
      { name: 'score', type: 'uint256' },
      { name: 'isFriend', type: 'bool' },
    ]}],
  },
  {
    name: 'getPlayerAchievements',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '_player', type: 'address' }],
    outputs: [{ name: '', type: 'bool[]' }],
  },
  {
    name: 'hasAchievement',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: '_player', type: 'address' },
      { name: '_achievement', type: 'uint8' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getFriends',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '_player', type: 'address' }],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    name: 'calculateAnswerHash',
    type: 'function',
    stateMutability: 'pure',
    inputs: [{ name: '_answer', type: 'string' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'hasPlayerBoughtHint',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '_player', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
] as const
